// Generated from product-list.json (image URLs omitted). Extra entries at the end have no price data.
const PRODUCTS = [
  {
    "id": 18273,
    "name": "PS5 + Games (100+) + 1 Controller",
    "rating": 4.6,
    "booked": 649,
    "tag": "Trending",
    "rent": 200,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 20242,
    "name": "PS5 All in one Combo + 2 Controllers",
    "rating": 4.5,
    "booked": 604,
    "tag": "Trending",
    "rent": 440,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 18255,
    "name": "PS5 + Games (100+) + 2 Controllers",
    "rating": 4.8,
    "booked": 397,
    "tag": "Trending",
    "rent": 260,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 20105,
    "name": "FC25 + 2 Controllers Combo",
    "rating": 4.8,
    "booked": 209,
    "tag": "Trending",
    "rent": 165,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 8185,
    "name": "PS5 + 1 Controller (Disc or Digital) (No Games Included)",
    "rating": 4.8,
    "booked": 236,
    "tag": "",
    "rent": 160,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 18117,
    "name": "PS5 + EA Play + 2 Controllers",
    "rating": 4.8,
    "booked": 167,
    "tag": "",
    "rent": 260,
    "outOfStock": true,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 19716,
    "name": "PS5 All in one Combo + 1 Controller",
    "rating": 4.5,
    "booked": 187,
    "tag": "Trending",
    "rent": 260,
    "outOfStock": true,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 19680,
    "name": "PS5 + 2 Controllers (Disc or Digital) (No Games Included)",
    "rating": 4.2,
    "booked": 210,
    "tag": "",
    "rent": 200,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 17795,
    "name": "God Of War Ragnarök + 1 Controller (Digital Game)",
    "rating": 4.6,
    "booked": 164,
    "tag": "",
    "rent": 200,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 18055,
    "name": "PS5 + EA Play + 1 Controller",
    "rating": 4.5,
    "booked": 211,
    "tag": "",
    "rent": 180,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 20104,
    "name": "Uncharted Series + 1 Controller (Digital Game)",
    "rating": 4.6,
    "booked": 171,
    "tag": "",
    "rent": 200,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 20103,
    "name": "Cricket 24 + 2 Controllers (Digital Game)",
    "rating": 4.8,
    "booked": 186,
    "tag": "",
    "rent": 200,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 36028,
    "name": "PS5 + FC26 + 1 Controller",
    "rating": 4.8,
    "booked": 2527,
    "tag": "New",
    "rent": 310,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 20102,
    "name": "Ghost of Tsushima + 1 Controller (Digital Game)",
    "rating": 4.6,
    "booked": 140,
    "tag": "",
    "rent": 200,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 20224,
    "name": "PS5 Mega Racing Wheel Combo",
    "rating": 4.8,
    "booked": 139,
    "tag": "",
    "rent": 310,
    "outOfStock": true,
    "cat": "PS5 Console",
    "icon": "i-wheel"
  },
  {
    "id": 36039,
    "name": "PS5 + FC26 + 2 Controllers",
    "rating": 4.8,
    "booked": 1524,
    "tag": "New",
    "rent": 310,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 20098,
    "name": "FC24 + 2 Controllers (Digital Game)",
    "rating": 4.8,
    "booked": 165,
    "tag": "",
    "rent": 200,
    "outOfStock": true,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 36050,
    "name": "PS5 + FC26 + 4 Controllers",
    "rating": 4.8,
    "booked": 1224,
    "tag": "New",
    "rent": 310,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 20100,
    "name": "Spider-Man Miles Morales + 1 Controller (Digital Game)",
    "rating": 4.6,
    "booked": 123,
    "tag": "",
    "rent": 200,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 37512,
    "name": "PS5 + FC27 + 2 Controllers",
    "rating": 0,
    "booked": 652,
    "tag": "New",
    "rent": 300,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 37501,
    "name": "PS5 + FC27 + 1 Controller",
    "rating": 0,
    "booked": 658,
    "tag": "New",
    "rent": 250,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 37534,
    "name": "PS5 + FC27 + 4 Controllers",
    "rating": 0,
    "booked": 651,
    "tag": "New",
    "rent": 350,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-console"
  },
  {
    "id": 37616,
    "name": "PlayStation Portal Remote Player",
    "rating": 0,
    "booked": 10000,
    "tag": "Vote to Launch",
    "rent": 158.25,
    "outOfStock": false,
    "cat": "PS5 Console",
    "icon": "i-pad"
  },
  {
    "id": null,
    "name": "Oculus Quest 3S",
    "rating": 0,
    "booked": 0,
    "tag": "Trending",
    "rent": null,
    "outOfStock": false,
    "cat": "VR",
    "icon": "i-vr"
  },
  {
    "id": null,
    "name": "Oculus Quest 2",
    "rating": 0,
    "booked": 0,
    "tag": "Trending",
    "rent": null,
    "outOfStock": false,
    "cat": "VR",
    "icon": "i-vr"
  },
  {
    "id": null,
    "name": "PS5 + GTA 6 with 1 Controller",
    "rating": 0,
    "booked": 0,
    "tag": "New",
    "rent": null,
    "outOfStock": false,
    "cat": "GTA VI",
    "icon": "i-console"
  },
  {
    "id": null,
    "name": "Xbox Series S (400+ Games) w/1 Controller-Model May Vary",
    "rating": 0,
    "booked": 0,
    "tag": "",
    "rent": null,
    "outOfStock": false,
    "cat": "Xbox Console",
    "icon": "i-pad"
  },
  {
    "id": null,
    "name": "Xbox Series S (200+ Games) w/2 Controllers-Model May Vary",
    "rating": 0,
    "booked": 0,
    "tag": "",
    "rent": null,
    "outOfStock": false,
    "cat": "Xbox Console",
    "icon": "i-pad"
  },
  {
    "id": null,
    "name": "Sony PlayStation PS VR2",
    "rating": 0,
    "booked": 0,
    "tag": "New",
    "rent": null,
    "outOfStock": false,
    "cat": "VR",
    "icon": "i-vr"
  }
];
